"use client";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { Provider } from "react-redux";
import { store } from "../redux/store";
import Footer from "./components/Footer/Footer";
import Navbar from "./components/Headers/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: 'IT Platform BD || Home',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html id="html" lang="en" className="container mx-auto">
      <head>
        <title>IT Platform BD || Home</title>
        <meta name="description" content="Description" />
      </head>
      <body className={`${inter.className} `}>
        <Provider store={store}>
          <Toaster position="top-center" reverseOrder={false} />
          <ProgressBar
            height="4px"
            color="#E77C01"
            options={{ showSpinner: false }}
            shallowRouting
          />
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
